package BaseFrege.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import BaseFrege.behavior.FDComplete__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import BaseFrege.behavior.Annotation__BehaviorDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.typesystem.inference.EquationInfo;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import jetbrains.mps.typesystem.inference.TypeChecker;
import BaseFrege.behavior.FunctionTypeHelper;
import BaseFrege.behavior.TypeWaiter;
import java.util.List;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import java.util.ArrayList;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.smodel.SModelUtil_new;

public class typeof_PatternFunction_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_PatternFunction_InferenceRule() {
  }
  public void applyRule(final SNode patternFunction, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    // Find the (typed) right side of the current definition 
    final SNode typedDefinitionNode = FDComplete__BehaviorDescriptor.getTypedDefinitionNode_id2LraaixmJl3.invoke(SNodeOperations.getNodeAncestor(patternFunction, MetaAdapterFactory.getConcept(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3d7900fe84e0386eL, "BaseFrege.structure.FDComplete"), false, false));

    // If there is a corresponding annotation, use it 
    final SNode annotation = Annotation__BehaviorDescriptor.findForVariable_idRvZSuXQxj1.invoke(SNodeOperations.asSConcept(MetaAdapterFactory.getConcept(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x7fa876a53c3d8c0L, "BaseFrege.structure.Annotation")), SNodeOperations.getNodeAncestor(patternFunction, MetaAdapterFactory.getConcept(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x7fa876a53c3d82fL, "BaseFrege.structure.Skeleton"), false, false), SLinkOperations.getTarget(patternFunction, MetaAdapterFactory.getContainmentLink(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3f5c5828a3895194L, 0x3f5c5828a3895195L, "name")));

    final int usedNumberOfArguments = ListSequence.fromList(SLinkOperations.getChildren(patternFunction, MetaAdapterFactory.getContainmentLink(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3f5c5828a3895194L, 0x3f5c5828a3895197L, "arguments"))).count();
    if ((annotation != null)) {
      // Infer the type based on the annotation 
      {
        SNode _nodeToCheck_1029348928467 = patternFunction;
        EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "2675082928409090155", 0, null);
        typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "2675082928409090159", true), (SNode) typeCheckingContext.typeOf(annotation, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "2675082928409090804", true), _info_12389875345);
      }
      {
        SNode _nodeToCheck_1029348928467 = SLinkOperations.getTarget(SLinkOperations.getTarget(patternFunction, MetaAdapterFactory.getContainmentLink(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3f5c5828a3895194L, 0x3f5c5828a3895195L, "name")), MetaAdapterFactory.getContainmentLink(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3f5c5828a3895192L, 0x7fc1a9722da278d3L, "_typeFilledByParent"));
        EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "2675082928409090161", 0, null);
        typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "2675082928409090165", true), (SNode) typeCheckingContext.typeOf(annotation, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "2675082928409090924", true), _info_12389875345);
      }

      // Check that the annotation is actually a function with the correct number of parameters 
      {
        final SNode annotationType = typeCheckingContext.typeOf(annotation, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "9205825421180051345", true);
        typeCheckingContext.whenConcrete(annotationType, new Runnable() {
          public void run() {
            if (SNodeOperations.isInstanceOf(typeCheckingContext.getExpandedNode(annotationType), MetaAdapterFactory.getConcept(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x534698153447f872L, "BaseFrege.structure.FunctionTypeNode"))) {
              // Function with arguments 
              final SNode ftn = SNodeOperations.cast(typeCheckingContext.getExpandedNode(annotationType), MetaAdapterFactory.getConcept(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x534698153447f872L, "BaseFrege.structure.FunctionTypeNode"));

              // Check the number of arguments 
              int realNumberOfArguments = ListSequence.fromList(SLinkOperations.getChildren(ftn, MetaAdapterFactory.getContainmentLink(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x534698153447f872L, 0x534698153447f873L, "arguments"))).count() - 1;
              if (realNumberOfArguments < usedNumberOfArguments) {
                {
                  MessageTarget errorTarget = new NodeMessageTarget();
                  IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(patternFunction, "Exceeded number of arguments, declared " + realNumberOfArguments + " but " + usedNumberOfArguments + " found.", "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "9205825421180119529", null, errorTarget);
                }
              }

              // Insert the types from annotation to children arguments 
              for (int i = 0; i < realNumberOfArguments; i++) {
                {
                  SNode _nodeToCheck_1029348928467 = SLinkOperations.getTarget(ListSequence.fromList(SLinkOperations.getChildren(patternFunction, MetaAdapterFactory.getContainmentLink(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3f5c5828a3895194L, 0x3f5c5828a3895197L, "arguments"))).getElement(i), MetaAdapterFactory.getContainmentLink(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3f5c5828a3895192L, 0x7fc1a9722da278d3L, "_typeFilledByParent"));
                  EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "9205825421180303966", 0, null);
                  typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "9205825421180303089", true), (SNode) ListSequence.fromList(SLinkOperations.getChildren(ftn, MetaAdapterFactory.getContainmentLink(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x534698153447f872L, 0x534698153447f873L, "arguments"))).getElement(i), _info_12389875345);
                }
              }

              // Compare the returning type from the definition with the annotation 
              {
                final SNode definitionType = typeCheckingContext.typeOf(typedDefinitionNode, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "5229219098489922476", true);
                typeCheckingContext.whenConcrete(definitionType, new Runnable() {
                  public void run() {
                    if (!(TypeChecker.getInstance().getSubtypingManager().isSubtype(typeCheckingContext.getExpandedNode(definitionType), FunctionTypeHelper.getReturnType(ftn, usedNumberOfArguments)))) {
                      {
                        MessageTarget errorTarget = new NodeMessageTarget();
                        IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(patternFunction, "Right side of the current definition does not correspond to the annotation.", "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "5229219098490620518", null, errorTarget);
                      }
                    }
                  }
                }, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "5229219098489915080", false, false);
              }
            } else {
              // Constant function 
              if (usedNumberOfArguments > 0) {
                {
                  MessageTarget errorTarget = new NodeMessageTarget();
                  IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(patternFunction, "Illegal pattern, expected a constant function.", "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "9205825421180054348", null, errorTarget);
                }
              }
            }
          }
        }, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "9205825421180048455", false, false);
      }

    } else {
      // There is no annotation available, so we have to construct the resulting type ourselves 
      for (SNode argument : ListSequence.fromList(SLinkOperations.getChildren(patternFunction, MetaAdapterFactory.getContainmentLink(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3f5c5828a3895194L, 0x3f5c5828a3895197L, "arguments")))) {
        {
          SNode _nodeToCheck_1029348928467 = SLinkOperations.getTarget(argument, MetaAdapterFactory.getContainmentLink(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3f5c5828a3895192L, 0x7fc1a9722da278d3L, "_typeFilledByParent"));
          EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "9205825421180372140", 0, null);
          typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "9205825421180364147", true), (SNode) _quotation_createNode_yc0jfs_a0a0b0a7a1(), _info_12389875345);
        }
      }

      // Wait for the resolution of the arguments' types 
      TypeWaiter tw = new TypeWaiter() {
        protected void waitForNode(final SNode node) {
          {
            final SNode nodeType = typeCheckingContext.typeOf(node, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "9205825421180384011", true);
            typeCheckingContext.whenConcrete(nodeType, new Runnable() {
              public void run() {
                nodeWaited(typeCheckingContext.getExpandedNode(nodeType));
              }
            }, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "9205825421180384006", false, false);
          }
        }

        protected void waitingFinished(List<SNode> nodeTypes) {
          SNode ftn = SConceptOperations.createNewNode(MetaAdapterFactory.getConcept(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x534698153447f872L, "BaseFrege.structure.FunctionTypeNode"));
          SNode resultingType = ListSequence.fromList(nodeTypes).removeLastElement();

          // Set arguments' types 
          for (SNode nodeType : ListSequence.fromList(nodeTypes)) {
            ListSequence.fromList(SLinkOperations.getChildren(ftn, MetaAdapterFactory.getContainmentLink(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x534698153447f872L, 0x534698153447f873L, "arguments"))).addElement(SNodeOperations.cast(nodeType, MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506dL, "jetbrains.mps.baseLanguage.structure.Type")));
          }

          // Merge the arguments with the right side 
          ftn = FunctionTypeHelper.mergeWithDefinitionType(ftn, SNodeOperations.cast(resultingType, MetaAdapterFactory.getConcept(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506dL, "jetbrains.mps.baseLanguage.structure.Type")));

          // Set the resulting type of the current node and the corresponding variable 
          {
            SNode _nodeToCheck_1029348928467 = patternFunction;
            EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "9205825421180384056", 0, null);
            typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "9205825421180384058", true), (SNode) ftn, _info_12389875345);
          }
          {
            SNode _nodeToCheck_1029348928467 = SLinkOperations.getTarget(SLinkOperations.getTarget(patternFunction, MetaAdapterFactory.getContainmentLink(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3f5c5828a3895194L, 0x3f5c5828a3895195L, "name")), MetaAdapterFactory.getContainmentLink(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3f5c5828a3895192L, 0x7fc1a9722da278d3L, "_typeFilledByParent"));
            EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "5229219098490014590", 0, null);
            typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:505d399a-118b-43d5-a757-1b10b70dd06b(BaseFrege.typesystem)", "5229219098490014594", true), (SNode) ftn, _info_12389875345);
          }
        }
      };
      List<SNode> nodesToWaitFor = ListSequence.fromList(new ArrayList<SNode>());
      ListSequence.fromList(nodesToWaitFor).addSequence(ListSequence.fromList(SLinkOperations.getChildren(patternFunction, MetaAdapterFactory.getContainmentLink(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3f5c5828a3895194L, 0x3f5c5828a3895197L, "arguments"))));
      ListSequence.fromList(nodesToWaitFor).addElement(typedDefinitionNode);
      tw.waitFor(nodesToWaitFor);
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return MetaAdapterFactory.getConcept(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3f5c5828a3895194L, "BaseFrege.structure.PatternFunction");
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }
  private static SNode _quotation_createNode_yc0jfs_a0a0b0a7a1() {
    PersistenceFacade facade = PersistenceFacade.getInstance();
    SNode quotedNode_1 = null;
    quotedNode_1 = SModelUtil_new.instantiateConceptDeclaration(MetaAdapterFactory.getConcept(MetaAdapterFactory.getLanguage(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, "BaseFrege"), 0x4f4212f5c8d48453L, "UnknownTypeNode"), null, null, false);
    return quotedNode_1;
  }
}
