package BaseFrege.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.cells.EditorCell;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.editor.runtime.cells.AbstractCellAction;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class ModuleNamePreFinal_RemoveTail {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.DELETE, new ModuleNamePreFinal_RemoveTail.ModuleNamePreFinal_RemoveTail_DELETE(node));
    editorCell.setAction(CellActionType.BACKSPACE, new ModuleNamePreFinal_RemoveTail.ModuleNamePreFinal_RemoveTail_BACKSPACE(node));
  }
  public static class ModuleNamePreFinal_RemoveTail_DELETE extends AbstractCellAction {
    /*package*/ SNode myNode;
    public ModuleNamePreFinal_RemoveTail_DELETE(SNode node) {
      this.myNode = node;
    }
    public String getDescriptionText() {
      return "Falls back to ModuleNameFinal upon removal of the tail.";
    }
    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }
    public void execute_internal(EditorContext editorContext, SNode node) {
      SNode mnf = SNodeFactoryOperations.createNewNode(SNodeFactoryOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3d75775c2fa108aaL, "BaseFrege.structure.ModuleNameFinal")), null);
      SPropertyOperations.set(mnf, MetaAdapterFactory.getProperty(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3d75775c2fa108aaL, 0x3d75775c2fa108abL, "name"), SPropertyOperations.getString(node, MetaAdapterFactory.getProperty(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3d75775c2fa108cbL, 0x3d75775c2fa108d2L, "head")));
      SNodeOperations.replaceWithAnother(node, mnf);
    }
  }
  public static class ModuleNamePreFinal_RemoveTail_BACKSPACE extends AbstractCellAction {
    /*package*/ SNode myNode;
    public ModuleNamePreFinal_RemoveTail_BACKSPACE(SNode node) {
      this.myNode = node;
    }
    public String getDescriptionText() {
      return "Falls back to ModuleNameFinal upon removal of the tail.";
    }
    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }
    public void execute_internal(EditorContext editorContext, SNode node) {
      SNode mnf = SNodeFactoryOperations.createNewNode(SNodeFactoryOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3d75775c2fa108aaL, "BaseFrege.structure.ModuleNameFinal")), null);
      SPropertyOperations.set(mnf, MetaAdapterFactory.getProperty(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3d75775c2fa108aaL, 0x3d75775c2fa108abL, "name"), SPropertyOperations.getString(node, MetaAdapterFactory.getProperty(0x90eaf9a4a968473cL, 0x8aedfef10c04a5dfL, 0x3d75775c2fa108cbL, 0x3d75775c2fa108d2L, "head")));
      SNodeOperations.replaceWithAnother(node, mnf);
    }
  }
}
